defmodule Frameshift.GenerationTest do
  use ExUnit.Case, async: false

  alias Frameshift.Generation
  alias Frameshift.Library

  defmodule FixtureProvider do
    @behaviour Frameshift.Generation.Provider

    @impl true
    def id, do: "fixture-local"

    @impl true
    def preflight(context) do
      send(context.test_pid, :provider_preflight)

      if context[:available] == false do
        {:error, :not_available}
      else
        {:ok,
         %{
           provider_id: "fixture-local",
           model: "fixture-model-v1",
           destination: :local,
           capabilities: %{"still" => true},
           disclosures: %{"costClass" => "local-compute"}
         }}
      end
    end

    @impl true
    def generate(_request, context) do
      send(context.test_pid, {:provider_generate, context.secret})

      {:ok,
       %{
         bytes: "fixture generated bytes",
         width: 16,
         height: 16,
         media_type: context[:media_type] || "image/png",
         result_id: "fixture-result-1"
       }}
    end
  end

  defmodule SlowProvider do
    @behaviour Frameshift.Generation.Provider

    @impl true
    def id, do: "slow-fixture"

    @impl true
    def preflight(_context) do
      {:ok,
       %{
         provider_id: "slow-fixture",
         model: "fixture-model-v1",
         destination: :local,
         capabilities: %{},
         disclosures: %{}
       }}
    end

    @impl true
    def generate(_request, _context) do
      Process.sleep(1_000)
      {:error, :unexpected_completion}
    end
  end

  setup do
    data_dir =
      Path.join(
        System.tmp_dir!(),
        "frameshift-generation-test-#{System.unique_integer([:positive, :monotonic])}"
      )

    on_exit(fn -> File.rm_rf!(data_dir) end)
    {:ok, library} = Library.start_link(data_dir: data_dir, name: nil)
    %{library: library, data_dir: data_dir}
  end

  test "an explicit provider result is cached across restart without persisting its context", %{
    library: library,
    data_dir: data_dir
  } do
    context = %{test_pid: self(), secret: "provider-secret-value"}

    assert {:ok, generated} =
             Generation.generate(library, FixtureProvider, request(),
               provider_context: context,
               timeout_ms: 500
             )

    assert generated[:cache] == :miss
    assert_receive :provider_preflight
    assert_receive {:provider_generate, "provider-secret-value"}

    assert generated["provenance_json"] == %{
             "kind" => "ai-generation",
             "model" => "fixture-model-v1",
             "provider" => "fixture-local",
             "resultId" => "fixture-result-1",
             "seed" => 7
           }

    assert generated["generation"] == %{
             "provider_result_id" => "fixture-result-1",
             "provenance" => generated["provenance_json"],
             "recipe_hash" => generated["generation_recipe_hash"]
           }

    refute inspect(generated) =~ "provider-secret-value"

    GenServer.stop(library)
    {:ok, restarted} = Library.start_link(data_dir: data_dir, name: nil)

    assert {:ok, cached} =
             Generation.generate(restarted, FixtureProvider, request(),
               provider_context: %{test_pid: self(), available: false, secret: "different"},
               timeout_ms: 500
             )

    assert cached[:cache] == :hit
    refute_receive :provider_preflight, 20
    refute_receive {:provider_generate, _secret}, 20
  end

  test "a generation result can share immutable bytes with an imported master", %{
    library: library
  } do
    assert {:ok, imported} =
             Library.import_master(
               library,
               "fixture generated bytes",
               imported_attributes()
             )

    assert {:ok, generated} =
             Generation.generate(library, FixtureProvider, request(%{seed: 10}),
               provider_context: %{test_pid: self(), secret: "unused"},
               timeout_ms: 500
             )

    assert generated["digest"] == imported["digest"]
    assert generated["source_kind"] == "import"
    assert generated["generation"]["recipe_hash"]
    assert generated["generation"]["provider_result_id"] == "fixture-result-1"
  end

  test "edit mode records its immutable parent", %{library: library} do
    assert {:ok, parent} = Library.import_master(library, "parent bytes", imported_attributes())

    edit_request =
      request(%{
        instruction: "Make a restrained variation",
        mode: "edit",
        parent_digest: parent["digest"],
        seed: 13
      })

    assert {:ok, variant} =
             Generation.generate(library, FixtureProvider, edit_request,
               provider_context: %{test_pid: self(), secret: "unused"},
               timeout_ms: 500
             )

    assert variant["parent_digest"] == parent["digest"]
    assert variant["generation"]["recipe_hash"] == variant["generation_recipe_hash"]
  end

  test "preflight failure returns without generation or fallback", %{library: library} do
    context = %{test_pid: self(), available: false, secret: "unused"}

    assert {:error, {:provider, :not_available}} =
             Generation.generate(library, FixtureProvider, request(%{seed: 8}),
               provider_context: context,
               timeout_ms: 500
             )

    assert_receive :provider_preflight
    refute_receive {:provider_generate, _secret}, 20
  end

  test "provider work is terminated at its explicit deadline", %{library: library} do
    slow_request = request(%{provider_id: "slow-fixture", seed: 9})

    assert {:error, :provider_timeout} =
             Generation.generate(library, SlowProvider, slow_request, timeout_ms: 10)
  end

  test "provider identity, invalid requests, and motion results are rejected", %{library: library} do
    assert {:error, :provider_mismatch} =
             Generation.generate(library, FixtureProvider, request(%{provider_id: "other"}))

    assert {:error, :invalid_instruction} =
             Generation.generate(library, FixtureProvider, request(%{instruction: ""}))

    assert {:error, :invalid_mode_parent} =
             Generation.generate(library, FixtureProvider, request(%{mode: "edit", seed: 11}))

    assert {:error, :invalid_disclosure} =
             Generation.generate(
               library,
               FixtureProvider,
               request(%{
                 disclosure: %{"destination" => "cloud", "acknowledged" => false}
               })
             )

    assert {:error, :invalid_result_media_type} =
             Generation.generate(library, FixtureProvider, request(%{seed: 12}),
               provider_context: %{test_pid: self(), secret: "unused", media_type: "video/mp4"}
             )
  end

  defp request(overrides \\ %{}) do
    Map.merge(
      %{
        adapter_revision: "fixture-adapter-v1",
        application_revision: "frameshift-preview-v1",
        base_instruction: "Create one still artwork.",
        base_instruction_revision: "still-base-v1",
        disclosure: %{"destination" => "local", "acknowledged" => true},
        provider_id: "fixture-local",
        model: "fixture-model-v1",
        instruction: "A quiet geometric still",
        negative_instruction: "",
        mode: "generate",
        parameters: %{"quality" => "preview"},
        reproducibility: "deterministic",
        seed: 7,
        target_profile_id: "experimental-rgb24",
        target_profile_revision: "preview-v1",
        title: "Generated Study"
      },
      overrides
    )
  end

  defp imported_attributes do
    %{
      title: "Imported Fixture",
      source_kind: :import,
      width: 16,
      height: 16,
      media_type: "image/png",
      provenance: %{"kind" => "local-import"}
    }
  end
end
