defmodule FrameshiftPlatform.Repo.Migrations.CatalogFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_source_documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:uri, :text, null: false)
      add(:revision, :text, null: false)
      add(:content_sha256, :text, null: false)
      add(:kind, :text, null: false)
      add(:observed_at, :utc_datetime_usec, null: false)
      add(:actor_id, :uuid, null: false)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:catalog_source_documents, [:uri, :revision],
             name: "catalog_source_documents_source_revision_index"
           )

    create table(:platform_audit_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:actor_id, :uuid, null: false)
      add(:subject_id, :uuid, null: false)
      add(:event, :text, null: false)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:platform_audit_events))

    drop_if_exists(
      unique_index(:catalog_source_documents, [:uri, :revision],
        name: "catalog_source_documents_source_revision_index"
      )
    )

    drop(table(:catalog_source_documents))
  end
end
